export const ENV = {
  API_URL: process.env.NEXT_PUBLIC_API_URL!,
  KEYCLOAK_URL: process.env.NEXT_PUBLIC_KEYCLOAK_URL!,
  KEYCLOAK_REALM: process.env.NEXT_PUBLIC_KEYCLOAK_REALM!,
  KEYCLOAK_CLIENT_ID: process.env.NEXT_PUBLIC_KEYCLOAK_CLIENT_ID!,
};

